app: # 应用基本配置
  env: docker # 环境名称
  port: 7888 # 服务监听端口号
  app_name: PropertyDetection # 应用名称
  app_url: http://127.0.0.1 # 应用域名
database:
  driver: mysql # 数据库驱动
  host: mysql9 # 域名
  port: 3306 # 端口号
  database: property_detection # 数据库名称
  username: root # 用户名
  password: admin_public # 密码
  charset: utf8mb4 # 编码格式
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: info # 日志级别
  enable_file_log_writer: false # 是否启用日志文件
  log_filename: sql.log # 日志文件名称
jwt:
  secret: 3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s
  jwt_ttl: 43200
minio:
  host: minio:9000 #Minio服务所在地址
  bucket: propertydetection #存储桶名称
  access_key: admin #访问的key
  secret_key: admin_public #访问的秘钥
  url: ${minio.host}/${minio.bucket}/